### ISSUE TITLE
ATOFormatFileController

### ISSUE THREAD

**Issue by edbrax** [stephaniaa/stephAssignment1#14]
The current plan is to use a separate controller class to open the CSV file which contains the ATO formatting information. Create this class, add a copy of the CSV file to the appropriate folder and confirm that we can open this file and store a pointer to it in MYOBtoATOcontroller.

**Comment by stephaniaa** [comment]
For this issue below I guess I can just copy the code that we used for the myob file controller? But then it would be a waste to have two classes that do the same thing, shouldn’t we have a base class for file opening and then use inheritance if there’s any differences?
I feel like gitignore is not working properly as it always tells me the ATOassignment.pro.user file is modified. Tried to fix it but no avail yet so will keep pushing  on and hopefully it becomes clear

**Comment by edbrax** [comment]
Not sure if replying to this will work. Where did you create this email? Let me know if you get this response.

I just thought that maybe the files listed in .gitignore need the correct path? You could try either relative or absolute paths. Don't forget to use forward slashes instead of backslashes. If that doesn't work, try using the "exclude" file in the .git/info folder.

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary

**Comment by stephaniaa** [comment]
Got it. Sorry just replied to your email rather than on github.
Yep I’ve tried relative paths. Played around with it a bit but will continue to do so

**Comment by edbrax** [comment]
No worries! I did just read somewhere that if git has ever tracked a particular file it will ignore gitignore. So you can only use gitignore for new files that have never been tracked. Sounds dumb, but maybe.

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary

**Comment by stephaniaa** [comment]
Copying my comments from the branch section:
At this stage I've created the class to get the CSV file the same way as the one for the MYOB file. We can always change them both to one class later if we want
I've been calling it 'CSV file' in the code when I should have used 'ATO file' as per what you wrote the other week but only realised too late.

**Comment by edbrax** [comment]
Looking good!

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary
