### ISSUE TITLE
OutputFileController

### ISSUE THREAD

**Issue by edbrax** [stephaniaa/stephAssignment1#16]
Create a class for OutputFileController. For now, you can simply save a simple string literal into the file to be saved. Think about the issues such as - should you allow the USER to name the file (should it check ATO requirements for file naming?) - where to save it (do we provide a dialog box to allow USER to decide where to save it).

**Comment by stephaniaa** [comment]
So far getting user to name file and select directory but can be changed. Also output is a text file at the moment

**Comment by edbrax** [comment]
That's all good.

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary

**Comment by stephaniaa** [comment]
Oh actually left a bunch of code in there I need to remove. Got it working then forgot I left some stuff there I didn’t use. Will make another branch and fix it now
